### ISSUE TITLE
Adding min and max attributes to Number template based on Range DataAnnotation

### ISSUE THREAD

**Issue by mikecole** [srkirkland/Html5MvcTemplates#5]
Would this be a worthy addition?

HTML5 min/max on input: http://stackoverflow.com/questions/8354975/how-to-add-maxlength-for-html5-input-type-number-element

Range validator: http://stackoverflow.com/questions/7256753/min-max-value-validators-in-asp-net-mvc

**Comment by srkirkland** [comment]
As far as I know there isn't a way to get validation annotations set on a property from inside of the Editor Templates, so adding MaxLenth or Min/Max attributes would seem to be impossible by this method without some other custom process.  Probably using the built in jquery validation stuff would be your best bet, as nice as this would be to have.

**Comment by mikecole** [comment]
What are your thoughts about a supplemental unobtrusive jQuery file that adds these bell and whistles, pulling from the validation values that MVC creates?

Something like so:

```
$("input[data-val-range-max]").each(function () {
    var value = $(this).data("val-range-max");
    $(this).attr("max", value);
});

$("input[data-val-range-min]").each(function () {
    var value = $(this).data("val-range-maxmin");
    $(this).attr("min", value);
});

$("input[data-val-length-max]").each(function () {
    var value = $(this).data("val-length-max");
    $(this).attr("maxlength", value);
});
```
